apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-v2-ingress
  namespace: caritas
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - appv2.oriso.site
    secretName: appv2-oriso-site-tls
  rules:
  - host: appv2.oriso.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-v2
            port:
              number: 9002

